// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69IEZtXxoGBsUoTwsR-4CQ8plVfOhROU',
    appId: '1:650918867939:web:a55be35fb107e5b65666d6',
    messagingSenderId: '650918867939',
    projectId: 'waiter-assi',
    authDomain: 'waiter-assi.firebaseapp.com',
    storageBucket: 'waiter-assi.firebasestorage.app',
    measurementId: 'G-4H5V43B9V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-vMpUMqWJAYIfTk1Obgt0KkSq8YVSAs',
    appId: '1:650918867939:android:83a1442317f955ed5666d6',
    messagingSenderId: '650918867939',
    projectId: 'waiter-assi',
    storageBucket: 'waiter-assi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCv4SzDq7T8NybSyXHVPeMPamgbs48xQ',
    appId: '1:650918867939:ios:e8ee61f40c62effb5666d6',
    messagingSenderId: '650918867939',
    projectId: 'waiter-assi',
    storageBucket: 'waiter-assi.firebasestorage.app',
    iosBundleId: 'com.example.waiterassi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfCv4SzDq7T8NybSyXHVPeMPamgbs48xQ',
    appId: '1:650918867939:ios:e8ee61f40c62effb5666d6',
    messagingSenderId: '650918867939',
    projectId: 'waiter-assi',
    storageBucket: 'waiter-assi.firebasestorage.app',
    iosBundleId: 'com.example.waiterassi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB69IEZtXxoGBsUoTwsR-4CQ8plVfOhROU',
    appId: '1:650918867939:web:58d12f84b9f0ee345666d6',
    messagingSenderId: '650918867939',
    projectId: 'waiter-assi',
    authDomain: 'waiter-assi.firebaseapp.com',
    storageBucket: 'waiter-assi.firebasestorage.app',
    measurementId: 'G-P8184K1LKM',
  );
}
